name = "vhdl"
repo = "https://github.com/alemuller/tree-sitter-vhdl"
commit = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5"
license = "MIT"
inventor = "U.S. Department of Defense"
year = 1983
description = "VHSIC Hardware Description Language; standardized as [IEEE 1076](https://standards.ieee.org/ieee/1076/7424/)."
wikipedia = "https://en.wikipedia.org/wiki/VHDL"
trivia = "Developed under the VHSIC program and standardized in 1987 as IEEE 1076; later revisions added numeric_std and child standards."

