name = "yaml"
repo = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"
commit = "7708026449bed86239b1cd5bce6e3c34dbca6415"
license = "MIT"
inventor = "Clark Evans, Ingy döt Net, Oren Ben-Kiki"
year = 2001
description = "Human-friendly data serialization language; official 1.2 spec at [yaml.org/spec/1.2.2](https://yaml.org/spec/1.2.2/)."
wikipedia = "https://en.wikipedia.org/wiki/YAML"
trivia = "Originally ‘Yet Another Markup Language’, later ‘YAML Ain’t Markup Language’; first proposed in 2001—see the [YAML history](https://yaml.org/spec/history/2001-01.html)."

