id = "cmake"
tier = 3
name = "CMake"
tag = "build"
icon = "devicon-plain:cmake"
repo = ""
commit = ""
license = ""
inventor = "Bill Hoffman"
year = 2000
description = "A cross-platform build system generator for C/C++ projects."
link = "https://en.wikipedia.org/wiki/CMake"
trivia = "CMake was originally developed to support the cross-platform build needs of the Insight Segmentation and Registration Toolkit (ITK)."

[[samples]]
path = "samples/catch2_cmakelists.cmake"
description = "Catch2 testing framework build configuration with options, subdirectories, and installation setup."
link = "https://github.com/catchorg/Catch2/blob/devel/CMakeLists.txt"
license = "BSL-1.0"
handpicked = true
