name = "zsh"
repo = "https://github.com/georgeharker/tree-sitter-zsh"
commit = "c50ded6979eb7aae8b8da5da9ac2e9e984804881"
license = "MIT"
inventor = "Paul Falstad"
year = 1990
description = "Extended Unix shell with rich scripting; reference manual at [zsh.sourceforge.io/Doc](https://zsh.sourceforge.io/Doc/)."
wikipedia = "https://en.wikipedia.org/wiki/Z_shell"
trivia = "Created by Falstad while at Princeton; named after TA Zhong Shao. The [zsh FAQ](https://zsh.sourceforge.io/FAQ/) documents its history and feature set."

